In [8]:
import tensorflow as tf
import numpy as np

x = tf.placeholder(tf.float32, (2, 10, 5))
y = tf.layers.conv1d(x, filters=12, kernel_size=3, padding='valid')
z = tf.reduce_max(y, axis=[1])

a = [i for i in range(100)]
a = np.asarray(a)
a = a.reshape((2, 10, 5))
print a.shape

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
z_val, y_val = sess.run([z, y], feed_dict={x:a})
print y_val.shape
print z_val.shape


(2, 10, 5)
(2, 8, 12)
(2, 12)


In [11]:
sentence = tf.placeholder(tf.int32, [3, 5])
labels = tf.expand_dims(sentence[:, 1], 1)
indices = tf.expand_dims(tf.range(0, 3, 1), 1)
concated = tf.concat([indices, labels], 1)
onehot_labels = tf.sparse_to_dense(concated, [3,15], 1.0, 0.0)

sentence_val = np.asarray([i for i in range(15)])
sentence_val = sentence_val.reshape((3,5))
print sentence_val

labels_val, indices_val, concated_val, onehot_labels_val = sess.run(
    [labels, indices, concated, onehot_labels], feed_dict={sentence: sentence_val})
print labels_val.shape
print labels_val
print indices_val.shape
print indices_val
print concated_val.shape
print concated_val
print onehot_labels_val.shape
print onehot_labels_val

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 1)
[[ 1]
 [ 6]
 [11]]
(3, 1)
[[0]
 [1]
 [2]]
(3, 2)
[[ 0  1]
 [ 1  6]
 [ 2 11]]
(3, 15)
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
